# Generated by Django 4.2.10 on 2024-02-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='pilot_logs/%Y/%m/%d/')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pilot Log',
                'verbose_name_plural': 'Pilot Logs',
            },
        ),
    ]
