# Generated by Django 4.2.10 on 2024-02-27 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='pilot_logs/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Pilot Log',
                'verbose_name_plural': 'Pilot Logs',
            },
        ),
    ]
